import { Section } from "@/components/layout/section";
import { Button } from "@/components/ui/button";
import { AddHoverState, ContactForm, CopyEmail } from "./page.client";
import { cn } from "@/lib/utils";
import { useId } from "react";
import Image from "next/image";

function HeroImage() {
  const panelNumber = 11;

  return (
    <div aria-hidden className="h-full w-full py-[15%] lg:py-[15%] px-[15%] lg:px-0 relative">
      <div className="absolute my-[25%] inset-0 z-20">
        <Image src="/bitcoin.webp" alt="bitcoin logo" fill className="object-contain" />
      </div>
      <div className="h-full aspect-square mx-auto rounded-full bg-linear-to-b from-accent-step-1 to-accent-step-2" />
      <div className="absolute inset-0 z-10 flex divide-background/32 divide-x">
        {Array.from({ length: panelNumber }).map((_, i) => (
          <div
            key={i}
            className="box-border bg-background/16 w-full h-full backdrop-blur-[36px]"
          />
        ))}
      </div>
    </div>
  );
}

function HeroSection() {
  return (
    <Section className="lg:h-[86dvh] lg:flex-row gap-40">
      <div className="relative mx-auto lg:mx-0 w-fit h-fit flex flex-col text-center lg:text-left mt-22.5">
        <h1 className="mb-6 whitespace-nowrap">
          <em>Honey</em> from
          <br />
          hard money
        </h1>
        <p className="text-lg-minus sm:text-lg-plus mb-7 w-0 min-w-full">
          Put your Bitcoin to work
        </p>
        <div className="w-[90dvw] mx-auto lg:hidden mb-7">
          <HeroImage />
        </div>
        <p className="mb-9 w-0 min-w-full px-10 sm:px-[15%] lg:px-0">
          Earn institutional-grade yield, powered by Bitcoin{" "}
          <span className="whitespace-nowrap">and real-world</span>
          assets.
        </p>
        <div className="flex space-x-4 w-0 min-w-full justify-center lg:justify-start">
          <Button>Request Access</Button>
          <Button variant={"secondary"}>Contact</Button>
        </div>
        <div className="lg:absolute -bottom-32 mt-18.75 lg:mt-0 left-0 flex flex-col lg:flex-row gap-10 whitespace-nowrap">
          <div>
          <p className="text-base-plus text-foreground mb-2">$100T+ Fixed-Income Market</p>
          <p>Access tokenized treasuries and credit.</p>
          </div>
          <div>
          <p className="text-base-plus text-foreground mb-2">$2.5–5% Target APY</p>
          <p>Backed by predictable cash flows. †</p>
          </div>
        </div>
      </div>
      <div className="hidden lg:block max-w-[75dvw] h-full ml-auto">
        <HeroImage />
      </div>
    </Section>
  );
}

function ContactSection() {
  return (
    <Section className="flex flex-col lg:flex-row sm:items-center gap-18.5">
      <div className="flex flex-col lg:pb-20 sm:mx-auto lg:mr-auto lg:ml-0 sm:items-center lg:items-start ">
        <h2>Get in Touch</h2>
        <p className="mb-8">or contact us by email</p>
        <CopyEmail />
      </div>
      <ContactForm />
    </Section>
  );
}

interface InstitutionalCardProps {
  label: string;
  title: string;
  text: string;
}

const InstitutionalCardsData = [
  {
    label: "Native",
    title: "Built on Bitcoin",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
  {
    label: "Scale",
    title: "Yield that Scales",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
  {
    label: "Flexibility",
    title: "Custom Solutions",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
  {
    label: "Risk",
    title: "Best-in-Class Risk Management",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
] satisfies InstitutionalCardProps[];


function IntitutionalCard(card: InstitutionalCardProps) {
  const id = useId()

  return (
    <li
      id={id}
      data-hover="false"
      className={cn(
        "group flex flex-col w-full overflow-hidden relative aspect-square sm:aspect-3/4 rounded-2xl pt-7 px-5",
        "border border-border transition-colors duration-200",
        "data-[hover=true]:bg-accent data-[hover=true]:border-accent-border"
      )}
    >
      <AddHoverState id={id} />

      <div
        id="gradient"
        className={cn(
          "absolute inset-0 opacity-0 blur-sm transition-opacity duration-200 pointer-events-none",
          "bg-[radial-gradient(50%_90%_at_50%_120%,var(--accent-step-1),var(--accent-step-2),transparent_70%)]",
          "group-data-[hover=true]:opacity-70"
        )}
      />

      <p>{card.label}</p>

      <div
        className={cn(
          "absolute px-5 pr-10 left-0 top-[calc(100%-120px)] sm:top-[calc(100%-90px)] transition-transform duration-250",
          "group-data-[hover=true]:-translate-y-40"
        )}
      >
        <h3>{card.title}</h3>

        <p
          className={cn(
            "mt-10 sm:mt-5 opacity-0 blur-sm transition-all duration-250",
            "group-data-[hover=true]:opacity-100",
            "group-data-[hover=true]:blur-none"
          )}
        >
          {card.text}
        </p>
      </div>
    </li>
  )
}


function InstitutionalSection() {
  return (
    <Section className="flex-col relative">
      <h2 className="mb-15!">Institutional by Design</h2>
      {/* TODO: not elegant but works */}
      <div className="absolute h-full hidden sm:block -left-4 sm:-left-10 lg:-left-25 top-0 w-20 z-40 bg-linear-to-l from-transparent to-background"/>
      <div className="absolute h-full hidden sm:block -right-4 sm:-right-10 lg:-right-25 top-0 w-20 z-40 bg-linear-to-r from-transparent to-background"/>
      <div className="-mx-4 sm:-mx-10 lg:-mx-25 px-4 sm:px-10 lg:px-25 overflow-scroll pb-5">
        <ul className="grid grid-cols-1 w-auto sm:grid-cols-4 gap-5 sm:w-280 lg:w-360">
          {InstitutionalCardsData.map((card) => (
            <IntitutionalCard {...card} key={card.label} />
          ))}
        </ul>
      </div>
    </Section>
  );
}

// HOW TO WORK

interface HowToWorkCardProps {
  step: string;
  title: string;
  text: string;
}

const HowToWorkCardData: HowToWorkCardProps[] = [
  {
    step: "01",
    title: "Verify",
    text: "Permissions set, custody stays put.",
  },
  {
    step: "02",
    title: "Allocate",
    text: "Pick a strategy; mint your on-chain position.",
  },
  {
    step: "03",
    title: "Harvest",
    text: "Earn yield, monitor, redeem.",
  },
];


function HowToWorkCard(card: HowToWorkCardProps) {

  const id = useId()

  return (
    <li 
    id={id} 
    data-hover="false"
    className="group bg-background relative px-7 pb-11.5 sm:pb-8 pt-0 -mt-2 min-w-60 sm:max-w-80 lg:max-w-60 w-full aspect-square lg:aspect-2/3 flex flex-col space-y-4">
      <AddHoverState id={id} />
      <p className="text-3xl font-serif text-foreground/5 group-data-[hover=true]:text-accent-step-2/20 transition-colors duration-250">{card.step}</p>
      <h4 className="mt-auto">{card.title}</h4>
      <p className="max-w-[18ch]">{card.text}</p>
    </li>
  );
}


function HowItWorksSection() {
  return (
    <Section className="relative flex flex-col xl:flex-row space-y-15">
      <div className="w-full">
        <h2>How it Works</h2>
        <p>Keep your custodian. Use our rails.</p>
      </div>

      <div
        id="gradinet"
        aria-hidden
        className="pointer-events-none absolute inset-0 blur-2xl opacity-40"
      >
        <div className="absolute -rotate-6 right-0 bottom-0 translate-x-1/2 translate-y-1/6 lg:translate-y-1/2 w-full h-[120%] sm:h-[80%] xl:h-[150%] rounded-full bg-[radial-gradient(100%_100%_at_50%_50%,var(--accent-step-1),var(--accent-step-2),transparent_50%)]" />
      </div>

      <ul className="flex gap-4.5 flex-col sm:flex-row">
        {HowToWorkCardData.map((card) => (
          <HowToWorkCard key={card.step} {...card} />
        ))}
      </ul>
    </Section>
  );
}

export default function Home() {
  return (
    <article>
      <HeroSection />
      <InstitutionalSection />
      <HowItWorksSection />
      <ContactSection />
    </article>
  );
}
