import { Section } from "@/components/layout/section";
import { Button } from "@/components/ui/button";
import { ContactForm, CopyEmail } from "./page.client";

function HeroImage() {
  const panelNumber = 11;

  return (
    <div className="h-full w-full py-[20%] lg:py-[15%] px-[20%] lg:px-0 relative">
      <div className="h-full aspect-square mx-auto bg-accent-step-1 rounded-full" />
      <div className="absolute inset-0 z-10 flex divide-background/32 divide-x">
        {Array.from({ length: panelNumber }).map((_, i) => (
          <div
            key={i}
            className="box-border bg-background/16 w-full h-full backdrop-blur-[36px]"
          />
        ))}
      </div>
    </div>
  );
}

function HeroSection() {
  return (
    <Section className="lg:h-[86dvh] lg:flex-row gap-10">
      <div className="mx-auto lg:mx-0 w-fit flex flex-col text-center lg:text-left lg:mt-20">
        <h1 className="mb-6 whitespace-nowrap">
          <em>Honey</em> from
          <br />
          hard money
        </h1>
        <p className="text-lg-minus sm:text-lg-plus mb-7 w-0 min-w-full">
          Put your Bitcoin to work
        </p>
        <div className="w-[75dvw] mx-auto lg:hidden mb-7">
          <HeroImage />
        </div>
        <p className="mb-9 w-0 min-w-full px-10 sm:px-[15%] lg:px-0">
          Earn institutional-grade yield, powered by Bitcoin{" "}
          <span className="whitespace-nowrap">and real-world</span>
          assets.
        </p>
        <div className="flex space-x-4 w-0 min-w-full justify-center lg:justify-start">
          <Button>Request Access</Button>
          <Button variant={"secondary"}>Contact</Button>
        </div>
        <div className="mt-auto"></div>
      </div>
      <div className="hidden lg:block max-w-[75dvw] h-full ml-auto">
        <HeroImage />
      </div>
    </Section>
  );
}

function ContactSection() {
  return (
    <Section className="flex flex-col lg:flex-row mb-80 sm:items-center gap-18.5">
      <div className="flex flex-col lg:pb-20 space-y-2 sm:mx-auto lg:mr-auto lg:ml-0 sm:items-center lg:items-start ">
        <h2>Get in Touch</h2>
        <p className="mb-8">or contact us by email</p>
        <CopyEmail />
      </div>
      <ContactForm />
    </Section>
  );
}

interface InstitutionalCardProps {
  label: string;
  title: string;
  text: string;
}

function IntitutionalCard(card: InstitutionalCardProps) {
  return (
    <li>
      <p>{card.label}</p>
      <p>{card.title}</p>
      <p>{card.text}</p>
    </li>
  );
}

const InstitutionalCardsData = [
  {
    label: "Native",
    title: "Built on Bitcoin",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
  {
    label: "Scale",
    title: "Yield that Scales",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
  {
    label: "Flexibility",
    title: "Custom Solutions",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
  {
    label: "Risk",
    title: "Best-in-Class Risk Management",
    text: "Yield is generated by top-tier institutional products from the names you know and trust",
  },
] satisfies InstitutionalCardProps[];

function InstitutionalSection() {
  return (
    <Section>
      <h2>Institutional by Design</h2>
      <ul>
        {InstitutionalCardsData.map((card) => (
          <IntitutionalCard {...card} key={card.label} />
        ))}
      </ul>
    </Section>
  );
}

interface HowToWorkCardProps {
  step: number;
  title: string;
  text: string;
}

const HowToWorkCardData: HowToWorkCardProps[] = [
  {
    step: 1,
    title: "Verify",
    text: "Permissions set, custody stays put.",
  },
  {
    step: 2,
    title: "Allocate",
    text: "Pick a strategy; mint your on-chain position.",
  },
  {
    step: 3,
    title: "Harvest",
    text: "Earn yield, monitor, redeem.",
  },
];

function HowToWorkCard(card: HowToWorkCardProps) {
  return (
    <li>
      <p>{card.step}</p>
      <p>{card.title}</p>
      <p>{card.text}</p>
    </li>
  );
}

function HowItWorksSection() {
  return (
    <Section>
      <h2>How it Works</h2>
      <p>Keep your custodian. Use our rails.</p>
      <ul>
        {HowToWorkCardData.map((card) => (
          <HowToWorkCard key={card.step} {...card} />
        ))}
      </ul>
    </Section>
  );
}

export default function Home() {
  return (
    <article>
      <HeroSection />
      <InstitutionalSection />
      <HowItWorksSection />
      <ContactSection />
    </article>
  );
}
